Repository okaneco/kmeans-colors, pull requests merged in 2025-04, with the labels that each got.

#62 Update rand crate and usage
  Cargo.lock
  Cargo.toml
  src/bin/kmeans_colors/utils.rs
  src/colors/kmeans.rs
  src/kmeans.rs
  src/plus_plus.rs
Labels: breaking, update-deps

#63 Bump version number to 0.7
  .github/workflows/rust-cd.yml
  .github/workflows/rust-ci.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: update

#64 Update CD script for Mac to aarch64
  .github/workflows/rust-cd.yml
Labels: bug
